version: '3.8'
services:
  pg_db:
    image: postgres:15
    container_name: pg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: licenser
    volumes:
      - ./store/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d licenser"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.0
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
  app:
    build: .
    ports:
      - "9080:9080"
    container_name: licenser
    depends_on:
      pg_db:
        condition: service_healthy    
    # restart: on-failure
